### ISSUE TITLE
Add support for GraphQL Schema administrative features

### ISSUE THREAD

**Issue by nicholsn** [stardog-union/pystardog#108]
The stardog HTTP API supports a number of administrative features for retrieving, listing, adding, and updating GraphQL schemas for a given database: https://stardog-union.github.io/http-docs/#tag/GraphQL

It would be great to have these supported in the `stardog.admin.Database` interface.

```
admin = stardog.Admin()
db = admin.database('test')
db.graphql_schemas()
db.add_graphql_schema('my-schema', schema_str)
etc...
```

**Comment by ctffarley** [comment]
Hi @nicholsn, this functionality exists already, just not in the place you might be expecting. You can use `stardog.connection.Connection.graphql()` to get a `GraphQL` object which has the functions you are looking for. This is documented here: https://pystardog.readthedocs.io/en/latest/source/stardog.html?highlight=graphql#stardog.connection.GraphQL
