### ISSUE TITLE
connection.begin should accept a reasoning parameter

### ISSUE THREAD

**Issue by snowell** [stardog-union/pystardog#25]
/{db}/transaction/begin (though not documented in apiary until just now) does accept a reasoning parameter to enable/disable reasoning connection-wide while the tx is happening. We need to allow users to set it here.

**Comment by cullan** [comment]
What should happen if the user creates a transaction without reasoning enabled and then tries to do queries in that transaction with reasoning? Should it raise an error?

**Comment by snowell** [comment]
I don't think an error is needed; any other APIs just allow Stardog to ignore the boolean passed in by the client in favor of the tx-level setting. Could output some sort of warning as a side effect if they don't match, but that's probably not needed either.
