### ISSUE TITLE
Add support for query datasets

### ISSUE THREAD

**Issue by PaulJackson123** [stardog-union/pystardog#32]
The `query` request takes query parameters `graph-uri`/`using-graph-uri`/`default-graph-uri` and `using-named-graph-uri`/`named-graph-uri` (I guess we only need `default-graph-uri` and `named-graph-uri`) which are not documented in the API, so it was missed in pystardog as well.

**Comment by PaulJackson123** [comment]
See https://community.stardog.com/t/how-to-get-pystardog-to-construct-from-a-named-graph-with-virtual-transparency-on/2418/10

**Comment by cullan** [comment]
This can be done by adding those as keyword parameters to the `select` and `graph` functions as it is. I will change the documentation to reflect that they are possible options.

**Comment by PaulJackson123** [comment]
When you create a QueryRequest, you provide a Dataset

https://github.com/stardog-union/stardog/blob/develop/protocols/http/client/main/src/com/complexible/stardog/protocols/http/client/QueryRequest.java#L99
https://github.com/stardog-union/stardog/blob/develop/stark/query/api/main/src/com/stardog/stark/query/Dataset.java

The `HTTPProtocol.parseQuery` method will set the Dataset's default graph(s) based on the `default-graph-uri` parameter and the names graphs based on the `named-graph-uri` parameter. 

Here's our java client:
https://github.com/stardog-union/stardog/blob/develop/protocols/http/client/main/src/com/complexible/stardog/protocols/http/client/HttpClientImpl.java#L747-L755

This explains datasets better than I ever will: https://www.w3.org/TR/sparql11-query/#rdfDataset

**Comment by PaulJackson123** [comment]
For `ask`, `select`, `plan` (once we support it),` graph`, and `paths`, we should allow the setting of `default-graph-uri` and `named-graph-uri`.

For `update` we should support `using-graph-uri`, `using-named-graph-uri`, `remove-graph-uri`, and `insert-graph-uri`.
