### ISSUE TITLE
Add support for adding/listing/delete cache target and cache. 

### ISSUE THREAD

**Issue by colleeseum** [stardog-union/pystardog#51]
### cache targets

- list cache targets
- adding cache target
- drop cache target
- orphan

### cache

- list cache
- add cache
- get cache
- get cache status
- refresh cache

**Comment by colleeseum** [comment]
I will create a PR later this week.

**Comment by mhgrove** [comment]
What's the overlap between this and what @cullan started with PR #37 ?

**Comment by colleeseum** [comment]
@joephayes  mentioned that the scaffolding was already done in PR#37. To answer the question thought, the PR seem to include more such as library restructuring. Will follow-up with @cullan .

**Comment by cullan** [comment]
@colleeseum I rebased the [feature/data_caching](https://github.com/stardog-union/pystardog/tree/feature/data_caching) branch from #37 onto develop so it should now have only the relevant changes.

**Comment by scardena** [comment]
Closing as this was solved here: https://github.com/stardog-union/pystardog/pull/59
