### ISSUE TITLE
Add support for update virtual graph

### ISSUE THREAD

**Issue by joephayes** [stardog-union/pystardog#56]
`new_virtual_graph` method uses a `POST` request. Updating a virtual graph requires a `PUT`. Add a "upsert" method for VGs (adds it is it does not exist, otherwise updates it?) 

https://stardog-union.github.io/http-docs/#operation/updateVG

**Comment by scardena** [comment]
Sorry for the late reply, prob you already figured this out, or worked around it. just in case, this was already implemented under the [vg.update() method](https://pystardog.readthedocs.io/en/latest/source/stardog.html#stardog.admin.VirtualGraph.update)
So in theory you should be able to update things like data source, mappings, or options separately.
I did add some modifications for updating though, in which you couldn't pass a datasource and options at the same time, which might be something you ran into. 

As an example, after this fix you should be able to do something like:
```
    ds = admin.new_datasource('music', music_options)
    vg = admin.new_virtual_graph('test_vg', mappings='', datasource=ds.name)
    vg.update('test_vg', mappings='', options={'mappings.syntax': 'SMS2'}, datasource=ds.name)
```
