### ISSUE TITLE
how to specify verify=False in pystardog?

### ISSUE THREAD

**Issue by ssfd7** [stardog-union/pystardog#80]
Running into certificate trust issues.

SSLError: HTTPSConnectionPool ... [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
This SO post https://levelup.gitconnected.com/solve-the-dreadful-certificate-issues-in-python-requests-module-2020d922c72f has a fix like :
```
requests.get('https://www.google.com', verify=False)
```
- But how do I do that with pystardog?
`
Thanks,

**Comment by scardena** [comment]
@ssfd7 can you provide a code snippet you are trying to run, and paste the entire stack trace?

**Comment by ssfd7** [comment]
Here it is - pay attention it is HTTPS - "S" at the end:

connection_details = {
  'endpoint': 'https://localhost:5820',
  'username': 'admin',
  'password': 'admin'
}
conn = stardog.Connection("d3fend", **connection_details)
query = """select * ?s where{?s ?p ?o}"""
csv_results = conn.select(query, content_type='text/csv')
df = pd.read_csv(io.BytesIO(csv_results))
df.head()

**Comment by scardena** [comment]
@ssfd7 do you strictly need to support SSL on localhost? because otherwise just removing the `s` from `https` in the endpoint should fix it. We run all our tests locally pointing at a non-secure stardog server, pointing them to `http://localhost:5820`
