### ISSUE TITLE
Best practice on Stardog connection? (create/close for each request or app-wise)

### ISSUE THREAD

**Issue by Larleyt** [stardog-union/pystardog#84]
From the docs it is unclear whether pystardog Connection class should be created/closed for each request/series of requests (basically, as a context manager) or to be created as a singleton for the whole app (more like usual DB client) and then closed on the app's shutdown with some event handler.

Could, please, anyone clarify on that matter? What is the best practice for the module?

**Comment by scardena** [comment]
sorry for the long delay on this. Yes, ideally we should use it as a context manager. it looks like we are currently not closing the connection properly, and it has been reported before: https://github.com/stardog-union/pystardog/issues/74
we will be fixing this soon.
