### ISSUE TITLE
Retrieval of stored queries is too expensive

### ISSUE THREAD

**Issue by mhgrove** [stardog-union/pystardog#89]
When we [get the list](https://github.com/stardog-union/pystardog/blob/develop/stardog/admin.py#L263) of stored queries from the server, the returned json actually has everything we need to create `StoredQuery` objects. Instead, the `StoredQuery` object makes a call back to the server to get data we already have locally, for every stored query returned in the list. This simple call takes 5+ seconds against doghouse. Users don't have a way to create a lightweight version of `StoredQuery` because the http call is part of its constructor. 

Below is a workaround for the behavior to get reasonable performance when calling the method. I think we should modify the implementation in `Admin` to something along similar lines.

```
def stored_queries(admin: stardog.Admin):
    r = admin.client.get('/admin/queries/stored', headers={'Accept': 'application/json'})
    return [SQ(**q) for q in r.json()['queries']]


class SQ(object):
    def __init__(self, **kwargs):
        self.name = kwargs.get("name")
        self.description = kwargs.get("description")
        self.query = kwargs.get("query")
        self.database = kwargs.get("database")
        self.creator = kwargs.get("creator")
        self.shared = kwargs.get("shared")
        self.reasoning = kwargs.get("reasoning")
```

**Comment by rmyers** [comment]
Instead of creating a lightweight version I'd suggest extending the current `StoredQuery` to accept an optional argument for  `details` that is already filled in. And if that is set skip the call to [`__refresh()`](https://github.com/stardog-union/pystardog/blob/fc131db119737b0f7cf0e991c5ff8184ae0cbb6d/stardog/admin.py#L1084)

**Comment by michaelthegreat** [comment]
@rmyers  created a PR to accept an optional argument for details that is already filled in and if that is set skip the call to __refresh()

https://github.com/stardog-union/pystardog/pull/98 

note: it says format is failed but I think it is the format pipeline itself unable to resolve some libraries. I ran black formatter on the changes before pushing.

**Comment by scardena** [comment]
fixed in https://github.com/stardog-union/pystardog/pull/107
