### ISSUE TITLE
pystardog 0.11 incompatible with python 3.7 (affects databricks 7.3 LTS)

### ISSUE THREAD

**Issue by AlBaker** [stardog-union/pystardog#96]
Databricks still has python 3.7 deployed in a current Databricks LTS runtime version 7.3. 

pystardog 0.11 uses syntax, specifically an f-string with equal expression, that will cause failures and inability to use pystardog in those databricks notebooks.

Workaround is to force a 0.10.0 install, e.g.
```
%pip install --upgrade pystardog==0.10.0 varname
```

Problematic line is here: https://github.com/stardog-union/pystardog/blob/develop/stardog/http/client.py#L40

Databricks release notes: 
https://docs.databricks.com/release-notes/runtime/releases.html

At least one of our clusters is on the 7.3 LTS version (release Sep 2020, EOL by Sep 2022). It looks like Databricks 8 upgraded the python version.

If this is the only place where we're using this f-string syntax sugar, my recommendation would be to change this line to something more compatible.

**Comment by scardena** [comment]
fixed in https://github.com/stardog-union/pystardog/pull/102
