### ISSUE TITLE
Small code-breaking typo

### ISSUE THREAD

**Issue by cgueret** [stardog-union/pystardog#97]
At this line: https://github.com/stardog-union/pystardog/blob/fc131db119737b0f7cf0e991c5ff8184ae0cbb6d/stardog/http/client.py#L40

the '=' in `f"{type(session)=} must be a valid requests.session.Session object."` breaks the code with an invalid syntax issue when the exception is raised.

**Comment by scardena** [comment]
what python version are you using? this syntax is valid from python 3.8 onwards. We will do a better job on advertising what python versions are supported in the short term.

**Comment by scardena** [comment]
fixed in https://github.com/stardog-union/pystardog/pull/102

**Comment by cgueret** [comment]
Indeed I'm using 3.7. For other projects using 3.8 and 3.9 I have no
issues. Do you imply that 3.7 is not supported for maybe other reasons? Or
is that line the only reason to require >3.7?
